branch-defaults:
  default:
    environment: fileUpload-staging1
  master-deploy:
    environment: fileUpload-prod
  staging-deploy:
    environment: fileUpload-staging1
global:
  application_name: testrun
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  profile: null
  sc: null
